### ISSUE TITLE
Utilizing a Mail List (collected by the OAuth process) 

### ISSUE THREAD

**Issue by DevByDJ** [TeachingData/SportProject#7]

**Comment by Brandonsilva1** [comment]
When the user logs in using the Oauth process their email connected to that oauth is put into a email list. We could send out weekly email updates about future games and the results of the previous games as an update. i mention only once a week to avoid feeling like spam and so that the content is more valuable.

**Comment by jsgreenwell** [comment]
Closed as duplicate
